#!/bin/sh

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
##############################################################################

APP_HOME=$( cd "$( dirname "$0" )" && pwd )
CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

if [ -x "$JAVA_HOME/bin/java" ]; then
    JAVA_EXECUTABLE="$JAVA_HOME/bin/java"
else
    JAVA_EXECUTABLE="java"
fi

exec "$JAVA_EXECUTABLE" -Xmx64m -Xms64m \
    -classpath "$CLASSPATH" \
    org.gradle.wrapper.GradleWrapperMain \
    "$@"
